version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: boothbooker-pg
    environment:
      POSTGRES_DB: boothbooker-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: